### ISSUE TITLE
`handle_links`: Should there be a way to open links using the default browser if it's not the current browser?

### ISSUE THREAD

**Issue by tomayac** [WICG/pwa-url-handler#42]
Imagine a user installs a PWA using _browser A_, since _browser A_ supports installation of PWAs. Further imagine the user's default browser is actually _browser B_. Should there be a fourth value `"default-browser"` that would be different from `"auto"` and that forces all links from a PWA installed from _browser A_ to open in the system default browser, that is, _browser B_?

```
"handle_links": "auto" | "preferred" | "not-preferred" | "default-browser"
```

(via http://twitter.com/kornelski/status/1493226187711262729)

**Comment by LuHuangMSFT** [comment]
I read the twitter thread and I think that's probably a different scenario altogether. `handle_links` is something that could control the experience for a link that comes to the browser, while the request is for links that leave the browser or PWA. 

I can imagine a feature where links within a PWA's web content are navigated differently than links within normal web content: the OS is asked to open the link instead of navigating directly in the app or browser window. That would be outside of the scope of the `handle_links` proposal.

**Comment by tomayac** [comment]
Thanks for clarifying. This feature request is then indeed out-of-scope. Closing.

**Comment by tomayac** [comment]
For people following along, I have moved this in an adapted form over to https://github.com/whatwg/html/issues/7628.
